# Configuration for Sonarr
sonarr_host: "http://localhost:8989" # Sonarr host address
sonarr_api: "your_sonarr_api_key" # Sonarr API key

# Configuration for Radarr
radarr_host: "http://localhost:7878" # Radarr host address
radarr_api: "your_radarr_api_key" # Radarr API key

# TMDB API key (The Movie Database)
tmdb_api: "your_tmdb_api_key" # TMDB API key

# Output directory for trailers
dir_backdrops: "backdrops" # Directory for storing trailers

# Base URL for YouTube links
yt_link_base: "https://www.youtube.com/watch?v=" # Base URL for YouTube links

# YouTube authentication information
auth_yt_user: "your_youtube_username" # YouTube username
auth_yt_pass: "your_youtube_password" # YouTube password

# Settings for downloading with Youtube-DL
no_warnings: True # Disable warnings
skip_intros: True # Skip video intros
max_length: 200 # Maximum acceptable video duration in seconds
thread_count: 4 # Number of threads for processing
buffer_size_ffmpeg: "1M" # Buffer size for FFMPEG

# Output file type for trailers
filetype: "mkv" # Output file type for trailers

# Sleep time between executions in hours
sleep_time: 6 # Time to wait between executions, in hours

# YouTube search keywords for trailers
yt_search_keywords: "official trailer" # Keywords for searching official trailers on YouTube

# Limit the download to one trailer per item
only_one_trailer: True # Limit to one trailer per item

# Minimum required free disk space in GB
min_free_space_gb: 5 # Minimum required free disk space in GB

# Default language for translation
default_locale: en # Default language for translation (e.g., en for English)

# Default language for trailers
default_language_trailer: en-EN # Default language for trailers (e.g., en-EN for English)

quiet_mode: False
