name: Build and Deploy Docs

on:
  push:
    branches: ["main"]

  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Remplacez par votre version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Get version
        id: meta
        run: echo ::set-output name=tags::$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")

      - name: Setup Sphinx documentation
        run: |
          mkdir -p docs
          cd docs
          sphinx-quickstart -q -p "Trailer Finder" -a "Kalibrado" -v "${{ steps.meta.outputs.tags || github.head_ref || github.ref_name }}"
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
